export const START_METRONOME = 'START_METRONOME';
export const STOP_METRONOME = 'STOP_METRONOME';

export const SET_CURRENT_BEAT = 'SET_CURRENT_BEAT';

export const SET_TIME_SIGNATURE = 'SET_TIME_SIGNATURE';

export const SET_TEMPO = 'SET_TEMPO';

export const SET_SOUND = 'SET_SOUND';

export const ADD_EMPHASISED_BEAT = 'ADD_EMPHASISED_BEAT';
export const REMOVE_EMPHASISED_BEAT = 'REMOVE_EMPHASISED_BEAT';